---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redis-reader-binding
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "rediscluster.chart" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
