---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ template "rediscluster.chart" . }}
