---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rediscluster.fullname" . }}-svc
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    chart: {{ template "rediscluster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if ne .Values.service.type "NodePort" }}
  clusterIP: "{{ .Values.service.clusterIP }}"
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
    loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  ports:
    - port: {{ .Values.service.clusterExternalPort }}
      targetPort: {{ .Values.service.clusterInternalPort }}
      name: {{ template "rediscluster.client.port" . }}
    - port: {{ .Values.service.clusterExternalGossipPort }}
      targetPort: {{ .Values.service.clusterInternalGossipPort }}
      name: {{ template "rediscluster.gossip.port" . }}
  selector:
    app: redis-node
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
