# Default values for redis-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 6
replicaTolerance: 1
serviceAccountName: rediscluster-sa

image:
  repository: parsenz/redis-node
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

# service:
#   type: ClusterIP
#   port: 80
service:
  type: "ClusterIP"
  clusterIP: "None"
  clusterInternalPort: 6379
  clusterExternalPort: 6379
  clusterInternalGossipPort: 16379
  clusterExternalGossipPort: 16379

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: standard
  neverForget: false
